version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/airlines
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1642
    depends_on:
      - db
    networks:
      - airlines-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=airlines
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1642
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - airlines-network

volumes:
  postgres-data:

networks:
  airlines-network:
    driver: bridge 